name: Check Components Changelog

on:
    pull_request:
        types: [opened, synchronize]
        paths:
            - 'packages/components/**'
            - '!packages/components/**/stories/**'
            - '!packages/components/src**/test/**'
jobs:
    check:
        name: Check @wordpress/components CHANGELOG
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
            - name: Check @wordpress/components CHANGELOG
              run: |
                  changelog_path="packages/components/CHANGELOG.md"

                  if git diff --quiet origin/trunk HEAD -- "$changelog_path"; then
                    echo "Please add a CHANGELOG entry to $changelog_path"
                    exit 1
                  fi
